# Generated by Django 5.1.4 on 2024-12-22 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excavation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('pottery', 'Pottery'), ('tools', 'Tools'), ('bones', 'Bones'), ('jewelry', 'Jewelry')], max_length=20)),
                ('depth', models.FloatField()),
                ('coordinates_north', models.FloatField()),
                ('coordinates_east', models.FloatField()),
                ('description', models.TextField()),
                ('length', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('excavation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_excavation.excavation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
