# Generated by Django 5.1.4 on 2024-12-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_excavation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='coordinates_east',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='coordinates_north',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('pottery', 'Pottery'), ('tools', 'Tools'), ('bones', 'Bones'), ('jewelry', 'Jewelry'), ('samples', 'Samples')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.FloatField(blank=True),
        ),
    ]
