# Generated by Django 5.1.4 on 2024-12-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_excavation', '0002_alter_item_coordinates_east_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
